name: Outdated package checks

# Run workflow on pull request to the main branch
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ master ]
  
  workflow_dispatch:

env:
  PROJECT_DIR: 'src/../'

jobs:
  outdated-packages-check:
    runs-on: ubuntu-latest

    steps:
      - uses: trossr32/outdated-packages-action@v0.0.6
        with:
          use-dotnet-outdated: false
          use-npm-outdated: true
          npm-project-directory: ${{ env.PROJECT_DIR }}