name: Playwright tests
on:
  pull_request:
    branches: [ staging, main, master ]
    types:
      - opened
      - synchronize
    paths:
      - '.github/workflows/playwright.yml'
      - 'src/**'
      - 'tests/playwright/**'
      - 'package.json'

  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    
    - name: Publish extension to dist folder
      run: |
           npm ci
           npm i grunt -g
           grunt release

    - name: Install test dependencies
      run: npm ci
      working-directory: test/playwright

    - name: Install playwright browser(s)
      run: npx playwright install --with-deps
      working-directory: test/playwright

    - name: Run playwright tests
      run: npx playwright test
      working-directory: test/playwright

    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: tests/playwright/playwright-report/
        retention-days: 30
